### ISSUE TITLE
Feature request: Allow role-based authentication

### ISSUE THREAD

**Issue by kevcube** [PostHog/s3-export-plugin#16]
For Posthog Cloud, this plugin should allow for role assumption rather than Access Keys and Secret Access Keys.

This would require the user to allow a Posthog-owned role or IAM user to assume a role in their AWS account, rather than giving Access Key/Secret Key to Posthog.

This is more secure because we can restrict access to the Posthog account/role that we authorize, and then there are no credentials to leak.

**Comment by xvello** [comment]
Closing as this plugin has been deprecated in favor of our [S3 destination for batch exports](https://posthog.com/docs/cdp/batch-exports/s3).
